type RemarkCategory = "EXCELLENT" | "GOOD" | "AVERAGE" | "POOR";

export const REMARK_BANK: Record<string, Record<RemarkCategory, string[]>> = {
  KG: {
    EXCELLENT: [
      "Very lively and enthusiastic in class activities.",
      "Interacts well with peers and shows good manners.",
      "Participates actively in singing, rhymes, and play.",
      "Motor skills are well developed for this level.",
      "Pays attention during lessons and follows instructions.",
      "Shows excitement towards learning every day.",
      "Very neat and organized for a young learner.",
      "Demonstrates confidence during group activities.",
      "Listens attentively during storytelling sessions.",
      "Always eager to try new classroom tasks.",
      "Learns quickly through play-based activities.",
      "Shows good independence for age.",
    ],
    GOOD: [
      "Making steady progress academically.",
      "Social skills are improving gradually.",
      "Participates well but needs encouragement at times.",
      "Understands lessons when guided properly.",
      "Good effort shown in class activities.",
      "Needs slight improvement in focus during lessons.",
      "Can follow simple instructions well.",
      "Shows interest in learning activities.",
      "Generally well-behaved in class.",
      "Improving in handwriting and coloring.",
    ],
    AVERAGE: [
      "Needs more encouragement to participate actively.",
      "Struggles with concentration during lessons.",
      "Still developing confidence in class activities.",
      "Requires regular supervision during tasks.",
      "Needs support with basic writing skills.",
      "Easily distracted during group activities.",
      "Participation in lessons is inconsistent.",
      "Needs more practice at home.",
      "Shows limited interest during lessons.",
      "Needs help developing independence.",
    ],
    POOR: [
      "Rarely participates in classroom activities.",
      "Has difficulty following simple instructions.",
      "Often disrupts lessons and playtime.",
      "Needs close supervision throughout the day.",
      "Shows little interest in class work.",
      "Frequently inattentive during lessons.",
      "Needs strong support both at school and home.",
      "Behavior affects learning negatively.",
      "Requires serious improvement in focus.",
      "Parental involvement is strongly advised.",
    ],
  },

  PRIMARY: {
    EXCELLENT: [
      "An excellent pupil with consistent academic performance.",
      "Reads fluently and writes clearly.",
      "Very disciplined and respectful in class.",
      "Shows strong understanding across subjects.",
      "Always completes assignments on time.",
      "Demonstrates confidence during lessons.",
      "Maintains neat workbooks consistently.",
      "Shows leadership qualities among peers.",
      "Pays close attention during lessons.",
      "Very punctual and responsible.",
      "A pleasure to teach.",
      "Exhibits strong learning habits.",
    ],
    GOOD: [
      "Good academic performance overall.",
      "Understands lessons but needs more consistency.",
      "Homework is mostly completed on time.",
      "Reads well but needs spelling improvement.",
      "Class participation is good.",
      "Behavior in class is satisfactory.",
      "Shows effort but needs more focus.",
      "Capable pupil with room for improvement.",
      "Listens well during lessons.",
      "Needs to improve speed in written work.",
    ],
    AVERAGE: [
      "Performance is average this term.",
      "Needs to take lessons more seriously.",
      "Often distracted during class activities.",
      "Homework completion is inconsistent.",
      "Reading habits need improvement.",
      "Talks excessively during lessons.",
      "Needs closer supervision to improve.",
      "Class participation is irregular.",
      "Shows potential but lacks discipline.",
      "Needs a structured study routine.",
    ],
    POOR: [
      "Academic performance is below expectation.",
      "Shows little interest in class work.",
      "Rarely completes assignments.",
      "Poor reading and writing skills.",
      "Behavior in class needs improvement.",
      "Attendance issues are affecting progress.",
      "Frequently inattentive during lessons.",
      "Needs urgent academic support.",
      "Parental supervision is required.",
      "Must change attitude towards learning.",
    ],
  },

  JHS: {
    EXCELLENT: [
      "An academically strong and focused student.",
      "Demonstrates excellent understanding of subjects.",
      "Very disciplined and responsible.",
      "Shows maturity and seriousness towards studies.",
      "Excellent preparation towards examinations.",
      "Actively participates in academic discussions.",
      "Consistently produces quality work.",
      "Good leadership potential.",
      "Highly motivated to succeed.",
      "Well-prepared for BECE challenges.",
      "Maintains positive learning attitude.",
      "Balances academics with responsibilities.",
    ],
    GOOD: [
      "Good performance but can do better.",
      "Understands lessons but needs more practice.",
      "Shows commitment to academic work.",
      "Needs to improve focus in some subjects.",
      "Good attitude towards learning.",
      "Homework completion is satisfactory.",
      "Participates during lessons when encouraged.",
      "Needs to manage time better.",
      "Potential for higher achievement.",
      "Requires consistency in effort.",
    ],
    AVERAGE: [
      "Academic performance is inconsistent.",
      "Needs to reduce distractions and focus more.",
      "Study habits require improvement.",
      "Often unprepared for lessons.",
      "Needs encouragement to ask questions.",
      "Homework submission is irregular.",
      "Shows average understanding of concepts.",
      "Needs to practice past questions.",
      "Peer influence affects seriousness.",
      "Needs stronger academic discipline.",
    ],
    POOR: [
      "Shows little seriousness towards academics.",
      "Performance is far below expectation.",
      "Frequently absent or late.",
      "Homework is rarely done.",
      "Poor attitude towards learning.",
      "Disruptive behavior affects progress.",
      "Needs urgent academic intervention.",
      "At risk of failing examinations.",
      "Parents must be involved immediately.",
      "Requires extra classes urgently.",
    ],
  },

  SHS: {
    EXCELLENT: [
      "An exceptional and highly disciplined student.",
      "Demonstrates strong academic independence.",
      "Excellent mastery of elective subjects.",
      "Consistently produces outstanding results.",
      "Displays strong critical thinking skills.",
      "Well-prepared for tertiary education.",
      "Shows leadership and responsibility.",
      "Highly focused on academic goals.",
      "Maintains excellent study habits.",
      "Very committed to academic excellence.",
      "Sets a good example for others.",
      "A pride to the school.",
    ],
    GOOD: [
      "Good academic performance overall.",
      "Understands concepts but needs refinement.",
      "Time management during exams needs improvement.",
      "Shows commitment but lacks consistency.",
      "Needs to improve essay writing skills.",
      "Good participation in class activities.",
      "Elective subjects require more attention.",
      "Capable of achieving higher grades.",
      "Needs to reduce distractions.",
      "Shows positive attitude to learning.",
    ],
    AVERAGE: [
      "Academic performance is average.",
      "Needs to take studies more seriously.",
      "Often distracted by social activities.",
      "Study habits are weak.",
      "Requires a more structured study plan.",
      "Prep hours are not fully utilized.",
      "Shows potential but lacks discipline.",
      "Needs improvement in examination technique.",
      "Assignments are sometimes avoided.",
      "Requires closer academic monitoring.",
    ],
    POOR: [
      "Academic commitment is very poor.",
      "Attendance issues are serious.",
      "Shows little interest in studies.",
      "Avoids assignments and assessments.",
      "Poor academic attitude persists.",
      "At risk of failing WASSCE.",
      "Requires urgent intervention.",
      "Parents/guardians must be informed.",
      "Needs a serious change in attitude.",
      "Academic future is in danger.",
    ],
  },
};

export const HEADMASTER_BANK = {
  GENERAL: {
    EXCELLENT: [
      "An outstanding academic performance. Keep it up.",
      "Excellent results. Continue working hard.",
      "Highly commendable effort this term.",
      "A very impressive academic achievement.",
      "Performance reflects dedication and discipline.",
      "Excellent progress shown across subjects.",
      "Maintain this standard in the coming term.",
      "A credit to the school.",
      "Consistently high academic performance.",
      "Results are truly commendable.",
      "An excellent example to others.",
      "Well-deserved commendation.",
    ],
    GOOD: [
      "Good performance overall.",
      "Steady progress has been made.",
      "Good effort but more work is needed.",
      "Encouraging results this term.",
      "With more focus, excellence can be achieved.",
      "Performance is satisfactory.",
      "Good improvement shown.",
      "Needs to aim higher next term.",
      "Results reflect moderate effort.",
      "Continue working harder.",
    ],
    AVERAGE: [
      "Performance is average.",
      "More seriousness is required next term.",
      "There is room for improvement.",
      "Results are not consistent.",
      "Needs to focus on weak areas.",
      "Academic effort must increase.",
      "Better supervision at home is advised.",
      "Needs stronger academic discipline.",
      "Results are below potential.",
      "More commitment is expected.",
    ],
    POOR: [
      "There is room for improvement.",
      "With more effort, better results can be achieved.",
      "Needs to develop better study habits.",
      "Encouragement and support will help.",
      "Showing signs of progress.",
      "Keep practicing and success will follow.",
      "Needs consistent academic support.",
      "Has potential to improve significantly.",
      "Extra attention will yield better results.",
      "With determination, improvement is possible.",
    ],
  },

  PROMOTIONAL: {
    Excellent: [
      "Excellent performance. PROMOTED with commendation.",
      "Outstanding results. PROMOTED to the next class.",
      "Exceptional achievement. Well deserved PROMOTION.",
      "PROMOTED with distinction. Keep excelling.",
      "Remarkable progress. PROMOTED successfully.",
      "PROMOTED. An exemplary student.",
    ],
    Good: [
      "PROMOTED to the next class. Well done.",
      "Good performance. PROMOTED successfully.",
      "PROMOTED. Keep working hard.",
      "Satisfactory progress. PROMOTED.",
      "PROMOTED. Maintain the positive attitude.",
      "PROMOTED. Continue improving.",
      "Good effort shown. PROMOTED.",
      "PROMOTED. Aim higher next term.",
    ],
    Encouraging: [
      "Shows potential for improvement.",
      "Making steady progress this term.",
      "With more effort, success will follow.",
      "Keep working hard and results will improve.",
      "Needs consistent practice to improve.",
      "Holiday revision is strongly recommended.",
      "Extra support will help achieve better results.",
      "Has the ability to do better.",
      "Improvement is expected next term.",
      "Needs to focus more on academics.",
    ],
  },
};

export const CONDUCT_TRAITS = [
  "Very disciplined and respectful.",
  "Punctual and responsible.",
  "Hardworking and focused.",
  "Neat and well-organized.",
  "Polite and cooperative.",
  "Friendly and respectful to others.",
  "Calm and attentive in class.",
  "Helpful and supportive to peers.",
  "Shows leadership qualities.",
  "Well-behaved and obedient.",
  "Needs to improve punctuality.",
  "Talkative but respectful.",
  "Quiet but attentive.",
  "Needs to improve classroom behavior.",
  "Sometimes playful but manageable.",
  "Shows good moral conduct.",
  "Needs closer supervision.",
  "Displays positive attitude.",
  "Needs to be more disciplined.",
  "Demonstrates good school ethics.",
];

export const INTERESTS = [
  "Football",
  "Athletics",
  "Netball",
  "Volleyball",
  "Table Tennis",
  "Reading Storybooks",
  "Drawing and Coloring",
  "Singing",
  "Traditional Drumming",
  "Cultural Dancing",
  "Music and Dance",
  "Computing",
  "Science Experiments",
  "Mathematics Activities",
  "Debating",
  "Spelling Bee",
  "Quiz Competitions",
  "Storytelling",
  "Gardening",
  "Keep Fit",
  "Cadet Training",
  "School Choir",
  "Environmental Club",
  "Religious and Moral Studies",
];
