// src/constants/subjects.ts
import type { SchoolLevel } from "../types";

export const SUBJECT_PRESETS: Record<SchoolLevel, string[]> = {
  KG: ["Language & Literacy", "Numeracy", "Our World Our People", "Creative Arts"],
  PRIMARY: [
    "English Language",
    "Mathematics",
    "Science",
    "Our World Our People",
    "History",
    "Religious & Moral Education",
    "Ghanaian Language",
    "Creative Arts",
    "Computing",
  ],
  JHS: [
    "English Language",
    "Mathematics",
    "Integrated Science",
    "Social Studies",
    "Religious & Moral Education",
    "Career Technology",
    "Creative Arts & Design",
    "Computing",
    "Ghanaian Language",
    "French",
    "Arabic Language",
  ],
  SHS: [
    "Core Mathematics",
    "Integrated Science",
    "English Language",
    "Social Studies",
    "Elective Mathematics",
    "Biology",
    "Physics",
    "Chemistry",
    "Economics",
    "Geography",
    "History",
    "Government",
    "Literature in English",
    "Agricultural Science",
    "Business Management",
    "Accounting",
    "Computing",
    "Information Communication Technology",
    "Food & Nutrition",
    "Design & Technology",
    "Physical Education",
    "General Knowledge in Arts",
    "Christian Religious Studies",
    "Islamic Religious Studies",
  ],
};
