/**
 * Supabase Client Configuration
 * Handles Supabase initialization and authentication
 */

// @ts-expect-error - Supabase package is optional, only installed when API_MODE=supabase
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import { isLocalMode } from "./config";

// Supabase configuration
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "";

// Database types (will be generated by Supabase CLI)
export interface Database {
  public: {
    Tables: {
      students: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          class_name: string;
          date_of_birth: string | null;
          gender: "Male" | "Female";
          attendance_present: number | null;
          teacher_remark: string | null;
          conduct: string | null;
          interest: string | null;
          picture_url: string | null;
          promotion_status: string | null;
          subjects: unknown; // JSONB field
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["students"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["students"]["Insert"]>;
      };
      settings: {
        Row: {
          id: string;
          user_id: string;
          school_name: string;
          academic_year: string;
          term: string;
          level: string;
          data: unknown; // JSONB field for all settings
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["settings"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["settings"]["Insert"]>;
      };
    };
  };
}

// Singleton Supabase client
let supabaseClient: SupabaseClient<Database> | null = null;

/**
 * Get or create Supabase client
 */
export function getSupabaseClient(): SupabaseClient<Database> | null {
  if (isLocalMode()) {
    return null; // Don't create client in local mode
  }

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error("Supabase credentials missing. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY");
    return null;
  }

  if (!supabaseClient) {
    supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
      },
      realtime: {
        params: {
          eventsPerSecond: 10,
        },
      },
    });
  }

  return supabaseClient;
}

/**
 * Check if user is authenticated
 */
export async function isAuthenticated(): Promise<boolean> {
  const supabase = getSupabaseClient();
  if (!supabase) return false;

  const { data } = await supabase.auth.getSession();
  return !!data.session;
}

/**
 * Get current user ID
 */
export async function getCurrentUserId(): Promise<string | null> {
  const supabase = getSupabaseClient();
  if (!supabase) return null;

  const { data } = await supabase.auth.getSession();
  return data.session?.user?.id || null;
}

/**
 * Sign out current user
 */
export async function signOut(): Promise<void> {
  const supabase = getSupabaseClient();
  if (!supabase) return;

  await supabase.auth.signOut();
}
